~ "high-scores.ua" ~ Hello

⍤⤙≍ [30 50, 20 70] scores [30 50, 20 70]                                           # List of scores?
⍤⤙≍ 30 latest [100 0, 90 30]                                                       # Latest score?
⍤⤙≍ 100 personal-best [40 100, 70]                                                 # Personal best?
⍤⤙≍ [100 90, 70] personal-top-three [10 30, 90 30, 100 20, 10 0, 30 40, 40 70, 70] # Personal top three from a list of scores?
⍤⤙≍ [30 20, 10] personal-top-three [20 10, 30]                                     # Personal top highest to lowest?
⍤⤙≍ [40 40, 30] personal-top-three [40 20, 40 30]                                  # Personal top when there is a tie?
⍤⤙≍ [70 30] personal-top-three [30 70]                                             # Personal top when there are less than 3?
⍤⤙≍ [40] personal-top-three [40]                                                   # Personal top when there is only one?
