~ "roman-numerals.ua" ~ Hello
needs exercism/test
⤙: test
27 tests

"1 is I"
(1 n:>roman)
"I"
=?

SKIP-REST-OF-TESTS

"2 is II"
(2 n:>roman)
"II"
=?

"3 is III"
(3 n:>roman)
"III"
=?

"4 is IV"
(4 n:>roman)
"IV"
=?

"5 is V"
(5 n:>roman)
"V"
=?

"6 is VI"
(6 n:>roman)
"VI"
=?

"9 is IX"
(9 n:>roman)
"IX"
=?

"27 is XXVII"
(27 n:>roman)
"XXVII"
=?

"48 is XLVIII"
(48 n:>roman)
"XLVIII"
=?

"49 is XLIX"
(49 n:>roman)
"XLIX"
=?

"59 is LIX"
(59 n:>roman)
"LIX"
=?

"93 is XCIII"
(93 n:>roman)
"XCIII"
=?

"141 is CXLI"
(141 n:>roman)
"CXLI"
=?

"163 is CLXIII"
(163 n:>roman)
"CLXIII"
=?

"402 is CDII"
(402 n:>roman)
"CDII"
=?

"575 is DLXXV"
(575 n:>roman)
"DLXXV"
=?

"911 is CMXI"
(911 n:>roman)
"CMXI"
=?

"1024 is MXXIV"
(1024 n:>roman)
"MXXIV"
=?

"3000 is MMM"
(3000 n:>roman)
"MMM"
=?

"16 is XVI"
(16 n:>roman)
"XVI"
=?

"66 is LXVI"
(66 n:>roman)
"LXVI"
=?

"166 is CLXVI"
(166 n:>roman)
"CLXVI"
=?

"666 is DCLXVI"
(666 n:>roman)
"DCLXVI"
=?

"1666 is MDCLXVI"
(1666 n:>roman)
"MDCLXVI"
=?

"3001 is MMMI"
(3001 n:>roman)
"MMMI"
=?

"3888 is MMMDCCCLXXXVIII"
(3888 n:>roman)
"MMMDCCCLXXXVIII"
=?

"3999 is MMMCMXCIX"
(3999 n:>roman)
"MMMCMXCIX"
=?

⤙end-of-tests
