~ "roman-numerals.ua" ~ Hello

# 1 is I
⍤⤙≍ "I" n:>roman 1

# 2 is II
⍤⤙≍ "II" n:>roman 2

# 3 is III
⍤⤙≍ "III" n:>roman 3

# 4 is IV
⍤⤙≍ "IV" n:>roman 4

# 5 is V
⍤⤙≍ "V" n:>roman 5

# 6 is VI
⍤⤙≍ "VI" n:>roman 6

# 9 is IX
⍤⤙≍ "IX" n:>roman 9

# 27 is XXVII
⍤⤙≍ "XXVII" n:>roman 27

# 48 is XLVIII
⍤⤙≍ "XLVIII" n:>roman 48

# 49 is XLIX
⍤⤙≍ "XLIX" n:>roman 49

# 59 is LIX
⍤⤙≍ "LIX" n:>roman 59

# 93 is XCIII
⍤⤙≍ "XCIII" n:>roman 93

# 141 is CXLI
⍤⤙≍ "CXLI" n:>roman 141

# 163 is CLXIII
⍤⤙≍ "CLXIII" n:>roman 163

# 402 is CDII
⍤⤙≍ "CDII" n:>roman 402

# 575 is DLXXV
⍤⤙≍ "DLXXV" n:>roman 575

# 911 is CMXI
⍤⤙≍ "CMXI" n:>roman 911

# 1024 is MXXIV
⍤⤙≍ "MXXIV" n:>roman 1024

# 3000 is MMM
⍤⤙≍ "MMM" n:>roman 3000

# 16 is XVI
⍤⤙≍ "XVI" n:>roman 16

# 66 is LXVI
⍤⤙≍ "LXVI" n:>roman 66

# 166 is CLXVI
⍤⤙≍ "CLXVI" n:>roman 166

# 666 is DCLXVI
⍤⤙≍ "DCLXVI" n:>roman 666

# 1666 is MDCLXVI
⍤⤙≍ "MDCLXVI" n:>roman 1666

# 3001 is MMMI
⍤⤙≍ "MMMI" n:>roman 3001

# 3888 is MMMDCCCLXXXVIII
⍤⤙≍ "MMMDCCCLXXXVIII" n:>roman 3888

# 3999 is MMMCMXCIX
⍤⤙≍ "MMMCMXCIX" n:>roman 3999
