~ "raindrops.ua" ~ Hello
needs exercism/test
⤙: test
18 tests

"the sound of 1 is 1"
(1 raindrops)
"1"
=?

SKIP-REST-OF-TESTS

"the sound for 10 is Plang as it has a factor 5"
(10 raindrops)
"Plang"
=?

"the sound for 105 is PlingPlangPlong as it has factors 3, 5 and 7"
(105 raindrops)
"PlingPlangPlong"
=?

"the sound for 14 is Plong as it has a factor of 7"
(14 raindrops)
"Plong"
=?

"the sound for 15 is PlingPlang as it has factors 3 and 5"
(15 raindrops)
"PlingPlang"
=?

"the sound for 21 is PlingPlong as it has factors 3 and 7"
(21 raindrops)
"PlingPlong"
=?

"the sound for 25 is Plang as it has a factor 5"
(25 raindrops)
"Plang"
=?

"the sound for 27 is Pling as it has a factor 3"
(27 raindrops)
"Pling"
=?

"the sound for 3 is Pling"
(3 raindrops)
"Pling"
=?

"the sound for 3125 is Plang as it has a factor 5"
(3125 raindrops)
"Plang"
=?

"the sound for 35 is PlangPlong as it has factors 5 and 7"
(35 raindrops)
"PlangPlong"
=?

"the sound for 49 is Plong as it has a factor 7"
(49 raindrops)
"Plong"
=?

"the sound for 5 is Plang"
(5 raindrops)
"Plang"
=?

"the sound for 52 is 52"
(52 raindrops)
"52"
=?

"the sound for 6 is Pling as it has a factor 3"
(6 raindrops)
"Pling"
=?

"the sound of 7 is Plong"
(7 raindrops)
"Plong"
=?

"2 to the power 3 does not make a raindrop sound as 3 is the exponent not the base"
(8 raindrops)
"8"
=?

"the sound of 9 is Pling as it has a factor 3"
(9 raindrops)
"Pling"
=?

⤙end-of-tests
