~ "raindrops.ua" ~ Hello

⍤⤙≍ "1" raindrops 1                 # the sound of 1 is 1?
⍤⤙≍ "Plang" raindrops 10            # the sound for 10 is Plang as it has a factor 5?
⍤⤙≍ "PlingPlangPlong" raindrops 105 # the sound for 105 is PlingPlangPlong as it has factors 3 5 and 7?
⍤⤙≍ "Plong" raindrops 14            # the sound for 14 is Plong as it has a factor of 7?
⍤⤙≍ "PlingPlang" raindrops 15       # the sound for 15 is PlingPlang as it has factors 3 and 5?
⍤⤙≍ "PlingPlong" raindrops 21       # the sound for 21 is PlingPlong as it has factors 3 and 7?
⍤⤙≍ "Plang" raindrops 25            # the sound for 25 is Plang as it has a factor 5?
⍤⤙≍ "Pling" raindrops 27            # the sound for 27 is Pling as it has a factor 3?
⍤⤙≍ "Pling" raindrops 3             # the sound for 3 is Pling?
⍤⤙≍ "Plang" raindrops 3125          # the sound for 3125 is Plang as it has a factor 5?
⍤⤙≍ "PlangPlong" raindrops 35       # the sound for 35 is PlangPlong as it has factors 5 and 7?
⍤⤙≍ "Plong" raindrops 49            # the sound for 49 is Plong as it has a factor 7?
⍤⤙≍ "Plang" raindrops 5             # the sound for 5 is Plang?
⍤⤙≍ "52" raindrops 52               # the sound for 52 is 52?
⍤⤙≍ "Pling" raindrops 6             # the sound for 6 is Pling as it has a factor 3?
⍤⤙≍ "Plong" raindrops 7             # the sound of 7 is Plong?
⍤⤙≍ "8" raindrops 8                 # 2 to the power 3 does not make a raindrop sound as 3 is the exponent not the base?
⍤⤙≍ "Pling" raindrops 9             # the sound of 9 is Pling as it has a factor 3?
