~ "space-age.ua" ~ Hello

"age on Earth"
(1000000000 "Earth" >age)
31.69
0.01
approx_=?

"age on Mercury"
(2134835688 "Mercury" >age)
280.88
0.01
approx_=?

"age on Venus"
(189839836 "Venus" >age)
9.78
0.01
approx_=?

"age on Mars"
(2129871239 "Mars" >age)
35.88
0.01
approx_=?

"age on Jupiter"
(901876382 "Jupiter" >age)
2.41
0.01
approx_=?

"age on Saturn"
(2000000000 "Saturn" >age)
2.15
0.01
approx_=?

"age on Uranus"
(1210123456 "Uranus" >age)
0.46
0.01
approx_=?

"age on Neptune"
(1821023456 "Neptune" >age)
0.35
0.01
approx_=?

"invalid planet causes error"
(680804807 "Sun" >age)
null?

