~ "difference-of-squares.ua" ~ Hello

# square of sum 1?
⍤⤙≍ 1 square-of-sum 1

# square of sum 5?
⍤⤙≍ 225 square-of-sum 5

# square of sum 100?
⍤⤙≍ 25502500 square-of-sum 100

# sum of squares 1?
⍤⤙≍ 1 sum-of-squares 1

# sum of squares 5?
⍤⤙≍ 55 sum-of-squares 5

# sum of squares 100?
⍤⤙≍ 338350 sum-of-squares 100

# difference of squares 1?
⍤⤙≍ 0 difference-of-squares 1

# difference of squares 5?
⍤⤙≍ 170 difference-of-squares 5

# difference of squares 100?
⍤⤙≍ 25164150 difference-of-squares 100
