~ "difference-of-squares.ua" ~ Hello

⍤⤙≍ 1 square-of-sum 1                  # square of sum 1?
⍤⤙≍ 225 square-of-sum 5                # square of sum 5?
⍤⤙≍ 25502500 square-of-sum 100         # square of sum 100?
⍤⤙≍ 1 sum-of-squares 1                 # sum of squares 1?
⍤⤙≍ 55 sum-of-squares 5                # sum of squares 5?
⍤⤙≍ 338350 sum-of-squares 100          # sum of squares 100?
⍤⤙≍ 0 difference-of-squares 1          # difference of squares 1?
⍤⤙≍ 170 difference-of-squares 5        # difference of squares 5?
⍤⤙≍ 25164150 difference-of-squares 100 # difference of squares 100?
