~ "difference-of-squares.ua" ~ Hello
"square of sum 1"
(1 square-of-sum)
1
=?

"square of sum 5"
(5 square-of-sum)
225
=?

"square of sum 100"
(100 square-of-sum)
25502500
=?

"sum of squares 1"
(1 sum-of-squares)
1
=?

"sum of squares 5"
(5 sum-of-squares)
55
=?

"sum of squares 100"
(100 sum-of-squares)
338350
=?

"difference of squares 1"
(1 difference-of-squares)
0
=?

"difference of squares 5"
(5 difference-of-squares)
170
=?

"difference of squares 100"
(100 difference-of-squares)
25164150
=?
