~ "kindergarten-garden.ua" ~ Hello

# garden with single student?
⍤⤙≍ ["radishes" "clover" "grass" "grass"] plants "RC\nGG" "Alice"

# different garden with single student?
⍤⤙≍ ["violets" "clover" "radishes" "clover"] plants "VC\nRC" "Alice"

# garden with two students?
⍤⤙≍ ["clover" "grass" "radishes" "clover"] plants "VVCG\nVVRC" "Bob"

# second student's garden?
⍤⤙≍ ["clover" "clover" "clover" "clover"] plants "VVCCGG\nVVCCGG" "Bob"

# third student's garden?
⍤⤙≍ ["grass" "grass" "grass" "grass"] plants "VVCCGG\nVVCCGG" "Charlie"

# for Alice, first student's garden?
⍤⤙≍ ["violets" "radishes" "violets" "radishes"] plants "VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Alice"

# for Bob, second student's garden?
⍤⤙≍ ["clover" "grass" "clover" "clover"] plants "VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Bob"

# for Charlie?
⍤⤙≍ ["violets" "violets" "clover" "grass"] plants "VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Charlie"

# for David?
⍤⤙≍ ["radishes" "violets" "clover" "radishes"] plants "VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "David"

# for Eve?
⍤⤙≍ ["clover" "grass" "radishes" "grass"] plants "VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Eve"

# for Fred?
⍤⤙≍ ["grass" "clover" "violets" "clover"] plants "VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Fred"

# for Ginny?
⍤⤙≍ ["clover" "grass" "grass" "clover"] plants "VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Ginny"

# for Harriet?
⍤⤙≍ ["violets" "radishes" "radishes" "violets"] plants "VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Harriet"

# for Ileana?
⍤⤙≍ ["grass" "clover" "violets" "clover"] plants "VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Ileana"

# for Joseph?
⍤⤙≍ ["violets" "clover" "violets" "grass"] plants "VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Joseph"

# for Kincaid, second to last student's garden?
⍤⤙≍ ["grass" "clover" "clover" "grass"] plants "VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Kincaid"

# for Larry, last student's garden?
⍤⤙≍ ["grass" "violets" "clover" "violets"] plants "VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Larry"
