~ "kindergarten-garden.ua" ~ Hello

⍤⤙≍ ["radishes" "clover" "grass" "grass"] plants "RC\nGG" "Alice"                                                     # garden with single student?
⍤⤙≍ ["violets" "clover" "radishes" "clover"] plants "VC\nRC" "Alice"                                                  # different garden with single student?
⍤⤙≍ ["clover" "grass" "radishes" "clover"] plants "VVCG\nVVRC" "Bob"                                                  # garden with two students?
⍤⤙≍ ["clover" "clover" "clover" "clover"] plants "VVCCGG\nVVCCGG" "Bob"                                               # second student's garden?
⍤⤙≍ ["grass" "grass" "grass" "grass"] plants "VVCCGG\nVVCCGG" "Charlie"                                               # third student's garden?
⍤⤙≍ ["violets" "radishes" "violets" "radishes"] plants "VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Alice"   # for Alice, first student's garden?
⍤⤙≍ ["clover" "grass" "clover" "clover"] plants "VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Bob"            # for Bob, second student's garden?
⍤⤙≍ ["violets" "violets" "clover" "grass"] plants "VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Charlie"      # for Charlie?
⍤⤙≍ ["radishes" "violets" "clover" "radishes"] plants "VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "David"    # for David?
⍤⤙≍ ["clover" "grass" "radishes" "grass"] plants "VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Eve"           # for Eve?
⍤⤙≍ ["grass" "clover" "violets" "clover"] plants "VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Fred"          # for Fred?
⍤⤙≍ ["clover" "grass" "grass" "clover"] plants "VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Ginny"           # for Ginny?
⍤⤙≍ ["violets" "radishes" "radishes" "violets"] plants "VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Harriet" # for Harriet?
⍤⤙≍ ["grass" "clover" "violets" "clover"] plants "VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Ileana"        # for Ileana?
⍤⤙≍ ["violets" "clover" "violets" "grass"] plants "VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Joseph"       # for Joseph?
⍤⤙≍ ["grass" "clover" "clover" "grass"] plants "VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Kincaid"         # for Kincaid, second to last student's garden?
⍤⤙≍ ["grass" "violets" "clover" "violets"] plants "VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Larry"        # for Larry, last student's garden?
