~ "kindergarten-garden.ua" ~ Hello

"garden with single student"
("RC\nGG" "Alice" plants)
["radishes", "clover", "grass", "grass"]
=?

"different garden with single student"
("VC\nRC" "Alice" plants)
["violets", "clover", "radishes", "clover"]
=?

"garden with two students"
("VVCG\nVVRC" "Bob" plants)
["clover", "grass", "radishes", "clover"]
=?

"second student's garden"
("VVCCGG\nVVCCGG" "Bob" plants)
["clover", "clover", "clover", "clover"]
=?

"third student's garden"
("VVCCGG\nVVCCGG" "Charlie" plants)
["grass", "grass", "grass", "grass"]
=?

"for Alice, first student's garden"
("VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Alice" plants)
["violets", "radishes", "violets", "radishes"]
=?

"for Bob, second student's garden"
("VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Bob" plants)
["clover", "grass", "clover", "clover"]
=?

"for Charlie"
("VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Charlie" plants)
["violets", "violets", "clover", "grass"]
=?

"for David"
("VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "David" plants)
["radishes", "violets", "clover", "radishes"]
=?

"for Eve"
("VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Eve" plants)
["clover", "grass", "radishes", "grass"]
=?

"for Fred"
("VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Fred" plants)
["grass", "clover", "violets", "clover"]
=?

"for Ginny"
("VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Ginny" plants)
["clover", "grass", "grass", "clover"]
=?

"for Harriet"
("VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Harriet" plants)
["violets", "radishes", "radishes", "violets"]
=?

"for Ileana"
("VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Ileana" plants)
["grass", "clover", "violets", "clover"]
=?

"for Joseph"
("VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Joseph" plants)
["violets", "clover", "violets", "grass"]
=?

"for Kincaid, second to last student's garden"
("VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Kincaid" plants)
["grass", "clover", "clover", "grass"]
=?

"for Larry, last student's garden"
("VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGCV" "Larry" plants)
["grass", "violets", "clover", "violets"]
=?
