~ "darts.ua" ~ Hello

"Missed target"
(-9 9 darts-score)
0
=?

"On the outer circle"
(0 10 darts-score)
1
=?

"On the middle circle"
(-5 0 darts-score)
5
=?

"On the inner circle"
(0 -1 darts-score)
10
=?

"Exactly on center"
(0 0 darts-score)
10
=?

"Near the center"
(-0.1 -0.1 darts-score)
10
=?

"Just within the inner circle"
(0.7 0.7 darts-score)
10
=?

"Just outside the inner circle"
(0.8 -0.8 darts-score)
5
=?

"Just within the middle circle"
(-3.5 3.5 darts-score)
5
=?

"Just outside the middle circle"
(-3.6 -3.6 darts-score)
1
=?

"Just within the outer circle"
(-7 7 darts-score)
1
=?

"Just outside the outer circle"
(7.1 -7.1 darts-score)
0
=?

"Asymmetric position between the inner and middle circles"
(0.5 -4 darts-score)
5
=?
