~ "acronym.ua" ~ Hello


"ignoring punctuation and casing"
("Complementary metal-oxide semiconductor" acronym)
"CMOS"
=?

SKIP-REST-OF-TESTS

"ignores punctuation"
("First In, First Out" acronym)
"FIFO"
=?

"from phrases with acronyms"
("GNU Image Manipulation Program" acronym)
"GIMP"
=?

"from phrases with apostrophes"
("Halley's Comet" acronym)
"HC"
=?

"from title case"
("Portable Network Graphics" acronym)
"PNG"
=?

"from lower case"
("Ruby on Rails" acronym)
"ROR"
=?

"from a very long abbreviation"
("Rolling On The Floor Laughing So Hard That My Dogs Came Over And Licked Me" acronym)
"ROTFLSHTMDCOALM"
=?

"from phrases with consecutive delimiters"
("Something - I made up from thin air" acronym)
"SIMUFTA"
=?

"from phrases with underscore emphasis"
("The Road _Not_ Taken" acronym)
"TRNT"
=?

⤙end-of-tests
