~ "acronym.ua" ~ Hello

⍤⤙≍ "CMOS" acronym "Complementary metal-oxide semiconductor"                                               # ignoring punctuation and casing?
⍤⤙≍ "FIFO" acronym "First In, First Out"                                                                   # ignores punctuation?
⍤⤙≍ "GIMP" acronym "GNU Image Manipulation Program"                                                        # from phrases with acronyms?
⍤⤙≍ "HC" acronym "Halley's Comet"                                                                          # from phrases with apostrophes?
⍤⤙≍ "PNG" acronym "Portable Network Graphics"                                                              # from title case?
⍤⤙≍ "ROR" acronym "Ruby on Rails"                                                                          # from lower case?
⍤⤙≍ "ROTFLSHTMDCOALM" acronym "Rolling On The Floor Laughing So Hard That My Dogs Came Over And Licked Me" # from a very long abbreviation?
⍤⤙≍ "SIMUFTA" acronym "Something - I made up from thin air"                                                # from phrases with consecutive delimiters?
⍤⤙≍ "TRNT" acronym "The Road _Not_ Taken"                                                                  # from phrases with underscore emphasis?
