~ "acronym.ua" ~ Hello

# ignoring punctuation and casing?
⍤⤙≍ "CMOS" acronym "Complementary metal-oxide semiconductor"

# ignores punctuation?
⍤⤙≍ "FIFO" acronym "First In, First Out"

# from phrases with acronyms?
⍤⤙≍ "GIMP" acronym "GNU Image Manipulation Program"

# from phrases with apostrophes?
⍤⤙≍ "HC" acronym "Halley's Comet"

# from title case?
⍤⤙≍ "PNG" acronym "Portable Network Graphics"

# from lower case?
⍤⤙≍ "ROR" acronym "Ruby on Rails"

# from a very long abbreviation?
⍤⤙≍ "ROTFLSHTMDCOALM" acronym "Rolling On The Floor Laughing So Hard That My Dogs Came Over And Licked Me"

# from phrases with consecutive delimiters?
⍤⤙≍ "SIMUFTA" acronym "Something - I made up from thin air"

# from phrases with underscore emphasis?
⍤⤙≍ "TRNT" acronym "The Road _Not_ Taken"
