~ "scrabble-score.ua" ~ Hello

# lowercase letter?
⍤⤙≍ 1 score "a"

# uppercase letter?
⍤⤙≍ 1 score "A"

# valuable letter?
⍤⤙≍ 4 score "f"

# short word?
⍤⤙≍ 2 score "at"

# short, valuable word?
⍤⤙≍ 12 score "zoo"

# medium word?
⍤⤙≍ 6 score "street"

# medium, valuable word?
⍤⤙≍ 22 score "quirky"

# long, mixed-case word?
⍤⤙≍ 41 score "OxyphenButazone"

# english-like word?
⍤⤙≍ 8 score "pinata"

# empty input?
⍤⤙≍ 0 score ""

# entire alphabet available?
⍤⤙≍ 87 score "abcdefghijklmnopqrstuvwxyz"
