~ "scrabble-score.ua" ~ Hello

⍤⤙≍ 1 score "a"                           # lowercase letter?
⍤⤙≍ 1 score "A"                           # uppercase letter?
⍤⤙≍ 4 score "f"                           # valuable letter?
⍤⤙≍ 2 score "at"                          # short word?
⍤⤙≍ 12 score "zoo"                        # short, valuable word?
⍤⤙≍ 6 score "street"                      # medium word?
⍤⤙≍ 22 score "quirky"                     # medium, valuable word?
⍤⤙≍ 41 score "OxyphenButazone"            # long, mixed-case word?
⍤⤙≍ 8 score "pinata"                      # english-like word?
⍤⤙≍ 0 score ""                            # empty input?
⍤⤙≍ 87 score "abcdefghijklmnopqrstuvwxyz" # entire alphabet available?
