~ "scrabble-score.ua" ~ Hello
needs exercism/test
⤙: test
11 tests

"lowercase letter"
("a" score)
1
=?

SKIP-REST-OF-TESTS

"uppercase letter"
("A" score)
1
=?

"valuable letter"
("f" score)
4
=?

"short word"
("at" score)
2
=?

"short, valuable word"
("zoo" score)
12
=?

"medium word"
("street" score)
6
=?

"medium, valuable word"
("quirky" score)
22
=?

"long, mixed-case word"
("OxyphenButazone" score)
41
=?

"english-like word"
("pinata" score)
8
=?

"empty input"
("" score)
0
=?

"entire alphabet available"
("abcdefghijklmnopqrstuvwxyz" score)
87
=?

⤙end-of-tests
