~ "two-fer.ua" ~ Hello

⍤⤙≍ "One for you, one for me." two-fer ""                              # Unnamed person test with empty string?
⍤⤙≍ "One for you, one for me." two-fer null                            # Unnamed person test with null?
⍤⤙≍ "One for Jedoon, one for me." two-fer "Jedoon"                     # One for the judge?
⍤⤙≍ "One for הַצְּלֶלְפּוֹנִי, one for me." two-fer "הַצְּלֶלְפּוֹנִי" # One for the Hebrew shade-facing one?
