~ "two-fer.ua" ~ Hello
needs exercism/test
⤙: test
4 tests

"Unnamed person test with empty string"
("" two-fer)
"One for you, one for me."
=?

SKIP-REST-OF-TESTS

"Unnamed person test with null"
(null two-fer)
"One for you, one for me."
=?

"One for the judge"
("Jedoon" two-fer)
"One for Jedoon, one for me."
=?

"One for the Hebrew shade-facing one"
("הַצְּלֶלְפּוֹנִי" two-fer)
"One for הַצְּלֶלְפּוֹנִי, one for me."
=?

⤙end-of-tests
