~ "armstrong-numbers.ua" ~ Hello

# Zero is an Armstrong number
⍤⤙≍ 1 armstrong? 0

# Single digit numbers are Armstrong numbers
⍤⤙≍ 1 armstrong? 5

# There are no 2 digit Armstrong Numbers
⍤⤙≍ 0 armstrong? 10

# Three digit number that is not an Armstrong number
⍤⤙≍ 0 armstrong? 100

# Three digit number that is an Armstrong number
⍤⤙≍ 1 armstrong? 153

# Four digit number that is an Armstrong number
⍤⤙≍ 1 armstrong? 9474

# Four digit number that is not an Armstrong number
⍤⤙≍ 0 armstrong? 9475

# Seven digit number that is not an Armstrong number
⍤⤙≍ 0 armstrong? 9926314

# Seven digit number that is an Armstrong number
⍤⤙≍ 1 armstrong? 9926315

# Armstrong number containing seven zeroes
⍤⤙≍ 1 armstrong? 186709961001538790100634132976990

# The largest and last Armstrong number
⍤⤙≍ 1 armstrong? 115132219018763992565095597973971522401

