~ "grains.ua" ~ Hello
needs exercism/test
⤙: test
11 tests

"grains on square 1"
(1 square)
1
=?

SKIP-REST-OF-TESTS

"grains on square 2"
(2 square)
2
=?

"grains on square 3"
(3 square)
4
=?

"grains on square 4"
(4 square)
8
=?

"grains on square 16"
(16 square)
32768
=?

"grains on square 32"
(32 square)
2147483648
=?

"grains on square 64"
(64 square)
9223372036854775808
=?

"square 0 is invalid"
(0 square)
null?

"negative square is invalid"
(-1 square)
null?

"square greater than 64 is invalid"
(65 square)
null?

"returns the total number of grains on the board"
(total)
18446744073709551615
=?

⤙end-of-tests
