~ "grains.ua" ~ Hello

# grains on square 1?
⍤⤙≍ 1 square 1

# grains on square 2?
⍤⤙≍ 2 square 2

# grains on square 3?
⍤⤙≍ 4 square 3

# grains on square 4?
⍤⤙≍ 8 square 4

# grains on square 16?
⍤⤙≍ 32768 square 16

# grains on square 32?
⍤⤙≍ 2147483648 square 32

# grains on square 64?
⍤⤙≍ 9223372036854775808 square 64

# square greater than 64 is invalid
⍤⤙≍ null? square 0

# square 0 is invali
⍤⤙≍ null? square `1

# negative square is invali
⍤⤙≍ null? square 65

"returns the total number of grains on the board"
(total)
18446744073709551615
=?
