~ "perfect-numbers.ua" ~ Hello

"Smallest perfect number is classified correctly"
(6 ⊛)
"perfect"
=?

"Medium perfect number is classified correctly"
(28 ⊛)
"perfect"
=?

"Large perfect number is classified correctly"
(33550336 ⊛)
"perfect"
=?

"Smallest abundant number is classified correctly"
(12 ⊛)
"abundant"
=?

"Medium abundant number is classified correctly"
(30 ⊛)
"abundant"
=?

"Large abundant number is classified correctly"
(33550335 ⊛)
"abundant"
=?

"Smallest prime deficient number is classified correctly"
(2 ⊛)
"deficient"
=?

"Smallest non-prime deficient number is classified correctly"
(4 ⊛)
"deficient"
=?

"Medium deficient number is classified correctly"
(32 ⊛)
"deficient"
=?

"Large deficient number is classified correctly"
(33550337 ⊛)
"deficient"
=?

"Edge case (no factors other than itself) is classified correctly"
(1 ⊛)
"deficient"
=?

"Zero is rejected (as it is not a positive integer)"
(0 ⊛)
null?

"Negative integer is rejected (as it is not a positive integer)"
(`1 ⊛)
null?
