~ "trinary.ua" ~ Hello

"1 is decimal 1"
("1" trinary>)
1
=?

"2 is decimal 2"
("2" trinary>)
2
=?

"10 is decimal 3"
("10" trinary>)
3
=?

"11 is decimal 4"
("11" trinary>)
4
=?

"100 is decimal 9"
("100" trinary>)
9
=?

"112 is decimal 14"
("112" trinary>)
14
=?

"222 is decimal 26"
("222" trinary>)
26
=?

"1122000120 is decimal 32091"
("1122000120" trinary>)
32091
=?

"invalid trinary is decimal 0"
("carrot" trinary>)
0
=?

"digits from 3 to 9 are invalid"
("123" trinary>)
0
=?
