~ "trinary.ua" ~ Hello

# 1 is decimal 1
⍤⤙≍ 1 trinary> "1"

# 2 is decimal 2
⍤⤙≍ 2 trinary> "2"

# 10 is decimal 3
⍤⤙≍ 3 trinary> "10"

# 11 is decimal 4
⍤⤙≍ 4 trinary> "11"

# 100 is decimal 9
⍤⤙≍ 9 trinary> "100"

# 112 is decimal 14
⍤⤙≍ 14 trinary> "112"

# 222 is decimal 26
⍤⤙≍ 26 trinary> "222"

# 1122000120 is decimal 32091
⍤⤙≍ 32091 trinary> "1122000120"

# invalid trinary is decimal 0
⍤⤙≍ 0 trinary> "carrot"

# digits from 3 to 9 are invalid
⍤⤙≍ 0 trinary> "123"
