~ "food-chain.ua" ~ Hello

⍤⤙≍ [
  # fly "I don't know why she swallowed the fly. Perhaps she'll die."
  "I know an old lady who swallowed a fly.", recite 1 1
]
=?
⍤⤙≍ [
  # spider "It wriggled and jiggled and tickled inside her.",
  "I know an old lady who swallowed a spider.", recite 2 2

  "She swallowed the spider to catch the fly.",
  "I don't know why she swallowed the fly. Perhaps she'll die."
]
=?
⍤⤙≍ [
  # bird "How absurd to swallow a bird!",
  "I know an old lady who swallowed a bird.", recite 3 3

  "She swallowed the bird to catch the spider that wriggled and jiggled and tickled inside her.",
  "She swallowed the spider to catch the fly.",
  "I don't know why she swallowed the fly. Perhaps she'll die."
]
=?
⍤⤙≍ [
  # cat "Imagine that, to swallow a cat!",
  "I know an old lady who swallowed a cat.", recite 4 4

  "She swallowed the cat to catch the bird.",
  "She swallowed the bird to catch the spider that wriggled and jiggled and tickled inside her.",
  "She swallowed the spider to catch the fly.",
  "I don't know why she swallowed the fly. Perhaps she'll die."
]
=?
⍤⤙≍ [
  # dog "What a hog, to swallow a dog!",
  "I know an old lady who swallowed a dog.", recite 5 5

  "She swallowed the dog to catch the cat.",
  "She swallowed the cat to catch the bird.",
  "She swallowed the bird to catch the spider that wriggled and jiggled and tickled inside her.",
  "She swallowed the spider to catch the fly.",
  "I don't know why she swallowed the fly. Perhaps she'll die."
]
=?
⍤⤙≍ [
  # goat "Just opened her throat and swallowed a goat!",
  "I know an old lady who swallowed a goat.", recite 6 6

  "She swallowed the goat to catch the dog.",
  "She swallowed the dog to catch the cat.",
  "She swallowed the cat to catch the bird.",
  "She swallowed the bird to catch the spider that wriggled and jiggled and tickled inside her.",
  "She swallowed the spider to catch the fly.",
  "I don't know why she swallowed the fly. Perhaps she'll die."
]
=?
⍤⤙≍ [
  # cow "I don't know how she swallowed a cow!",
  "I know an old lady who swallowed a cow.", recite 7 7

  "She swallowed the cow to catch the goat.",
  "She swallowed the goat to catch the dog.",
  "She swallowed the dog to catch the cat.",
  "She swallowed the cat to catch the bird.",
  "She swallowed the bird to catch the spider that wriggled and jiggled and tickled inside her.",
  "She swallowed the spider to catch the fly.",
  "I don't know why she swallowed the fly. Perhaps she'll die."
]
=?
⍤⤙≍ [
  # horse "She's dead, of course!"
  "I know an old lady who swallowed a horse.", recite 8 8
]
=?
⍤⤙≍ [
  # multiple verses "I don't know why she swallowed the fly. Perhaps she'll die.",
  "I know an old lady who swallowed a fly.", recite 1 3

  "",
  "I know an old lady who swallowed a spider.",
  "It wriggled and jiggled and tickled inside her.",
  "She swallowed the spider to catch the fly.",
  "I don't know why she swallowed the fly. Perhaps she'll die.",
  "",
  "I know an old lady who swallowed a bird.",
  "How absurd to swallow a bird!",
  "She swallowed the bird to catch the spider that wriggled and jiggled and tickled inside her.",
  "She swallowed the spider to catch the fly.",
  "I don't know why she swallowed the fly. Perhaps she'll die."
]
=?
⍤⤙≍ [
  # full song "I don't know why she swallowed the fly. Perhaps she'll die.",
  "I know an old lady who swallowed a fly.", recite 1 8

  "",
  "I know an old lady who swallowed a spider.",
  "It wriggled and jiggled and tickled inside her.",
  "She swallowed the spider to catch the fly.",
  "I don't know why she swallowed the fly. Perhaps she'll die.",
  "",
  "I know an old lady who swallowed a bird.",
  "How absurd to swallow a bird!",
  "She swallowed the bird to catch the spider that wriggled and jiggled and tickled inside her.",
  "She swallowed the spider to catch the fly.",
  "I don't know why she swallowed the fly. Perhaps she'll die.",
  "",
  "I know an old lady who swallowed a cat.",
  "Imagine that, to swallow a cat!",
  "She swallowed the cat to catch the bird.",
  "She swallowed the bird to catch the spider that wriggled and jiggled and tickled inside her.",
  "She swallowed the spider to catch the fly.",
  "I don't know why she swallowed the fly. Perhaps she'll die.",
  "",
  "I know an old lady who swallowed a dog.",
  "What a hog, to swallow a dog!",
  "She swallowed the dog to catch the cat.",
  "She swallowed the cat to catch the bird.",
  "She swallowed the bird to catch the spider that wriggled and jiggled and tickled inside her.",
  "She swallowed the spider to catch the fly.",
  "I don't know why she swallowed the fly. Perhaps she'll die.",
  "",
  "I know an old lady who swallowed a goat.",
  "Just opened her throat and swallowed a goat!",
  "She swallowed the goat to catch the dog.",
  "She swallowed the dog to catch the cat.",
  "She swallowed the cat to catch the bird.",
  "She swallowed the bird to catch the spider that wriggled and jiggled and tickled inside her.",
  "She swallowed the spider to catch the fly.",
  "I don't know why she swallowed the fly. Perhaps she'll die.",
  "",
  "I know an old lady who swallowed a cow.",
  "I don't know how she swallowed a cow!",
  "She swallowed the cow to catch the goat.",
  "She swallowed the goat to catch the dog.",
  "She swallowed the dog to catch the cat.",
  "She swallowed the cat to catch the bird.",
  "She swallowed the bird to catch the spider that wriggled and jiggled and tickled inside her.",
  "She swallowed the spider to catch the fly.",
  "I don't know why she swallowed the fly. Perhaps she'll die.",
  "",
  "I know an old lady who swallowed a horse.",
  "She's dead, of course!"
]
=?
