~ "bob.ua" ~ Hello
needs exercism/test
⤙: test
17 tests

"prolonged silence"
("    " bob)
"Fine. Be that way!"
=?

SKIP-REST-OF-TESTS

"silence"
("" bob)
"Fine. Be that way!"
=?

"shouting numbers"
("1, 2, 3 GO!" bob)
"Whoa, chill out!"
=?

"no letters"
("1, 2, 3" bob)
"Whatever."
=?

"question with no letters"
("4?" bob)
"Sure."
=?

"multiple line question"
("Does this cryogenic chamber make me look fat?\nno" bob)
"Whatever."
=?

"asking a question"
("Does this cryogenic chamber make me look fat?" bob)
"Sure."
=?

"statement containing question mark"
("Ending with ? means a question." bob)
"Whatever."
=?

"shouting with no exclamation mark"
("I HATE YOU" bob)
"Whoa, chill out!"
=?

"using acronyms in regular speech"
("It's OK if you don't want to go to the DMV." bob)
"Whatever."
=?

"speaking forcefully"
("Let's go make out behind the gym!" bob)
"Whatever."
=?

"stating something"
("Tom-ay-to, tom-aaaah-to." bob)
"Whatever."
=?

"shouting"
("WATCH OUT!" bob)
"Whoa, chill out!"
=?

"forceful question"
("WHAT THE HELL WERE YOU THINKING?" bob)
"Calm down, I know what I'm doing!"
=?

"prattling on"
("Wait! Hang on. Are you going to be OK?" bob)
"Sure."
=?

"asking a numeric question"
("You are, what, like 15?" bob)
"Sure."
=?

"shouting with special characters"
("ZOMG THE %^*@#$(*^ ZOMBIES ARE COMING!!11!!1!" bob)
"Whoa, chill out!"
=?

⤙end-of-tests
