~ "bob.ua" ~ Hello

⍤⤙≍ "Fine. Be that way!" bob "    "                                            # prolonged silence?
⍤⤙≍ "Fine. Be that way!" bob ""                                                # silence?
⍤⤙≍ "Whoa, chill out!" bob "1, 2, 3 GO!"                                       # shouting numbers?
⍤⤙≍ "Whatever." bob "1, 2, 3"                                                  # no letters?
⍤⤙≍ "Sure." bob "4?"                                                           # question with no letters?
⍤⤙≍ "Whatever." bob "Does this cryogenic chamber make me look fat?\nno"        # multiple line question?
⍤⤙≍ "Sure." bob "Does this cryogenic chamber make me look fat?"                # asking a question?
⍤⤙≍ "Whatever." bob "Ending with ? means a question."                          # statement containing question mark?
⍤⤙≍ "Whoa, chill out!" bob "I HATE YOU"                                        # shouting with no exclamation mark?
⍤⤙≍ "Whatever." bob "It's OK if you don't want to go to the DMV."              # using acronyms in regular speech?
⍤⤙≍ "Whatever." bob "Let's go make out behind the gym!"                        # speaking forcefully?
⍤⤙≍ "Whatever." bob "Tom-ay-to, tom-aaaah-to."                                 # stating something?
⍤⤙≍ "Whoa, chill out!" bob "WATCH OUT!"                                        # shouting?
⍤⤙≍ "Calm down, I know what I'm doing!" bob "WHAT THE HELL WERE YOU THINKING?" # forceful question?
⍤⤙≍ "Sure." bob "Wait! Hang on. Are you going to be OK?"                       # prattling on?
⍤⤙≍ "Sure." bob "You are, what, like 15?"                                      # asking a numeric question?
⍤⤙≍ "Whoa, chill out!" bob "ZOMG THE %^*@#$(*^ ZOMBIES ARE COMING!!11!!1!"     # shouting with special characters?
