~ "bob.ua" ~ Hello

# prolonged silence?
⍤⤙≍ "Fine. Be that way!" bob "    "

# silence?
⍤⤙≍ "Fine. Be that way!" bob ""

# shouting numbers?
⍤⤙≍ "Whoa, chill out!" bob "1 2 3 GO!"

# no letters?
⍤⤙≍ "Whatever." bob "1 2 3"

# question with no letters?
⍤⤙≍ "Sure." bob "4?"

# multiple line question?
⍤⤙≍ "Whatever." bob "Does this cryogenic chamber make me look fat?\nno"

# asking a question?
⍤⤙≍ "Sure." bob "Does this cryogenic chamber make me look fat?"

# statement containing question mark?
⍤⤙≍ "Whatever." bob "Ending with ? means a question."

# shouting with no exclamation mark?
⍤⤙≍ "Whoa, chill out!" bob "I HATE YOU"

# using acronyms in regular speech?
⍤⤙≍ "Whatever." bob "It's OK if you don't want to go to the DMV."

# speaking forcefully?
⍤⤙≍ "Whatever." bob "Let's go make out behind the gym!"

# stating something?
⍤⤙≍ "Whatever." bob "Tom-ay-to, tom-aaaah-to."

# shouting?
⍤⤙≍ "Whoa, chill out!" bob "WATCH OUT!"

# forceful question?
⍤⤙≍ "Calm down, I know what I'm doing!" bob "WHAT THE HELL WERE YOU THINKING?"

# prattling on?
⍤⤙≍ "Sure." bob "Wait! Hang on. Are you going to be OK?"

# asking a numeric question?
⍤⤙≍ "Sure." bob "You are, what, like 15?"

# shouting with special characters?
⍤⤙≍ "Whoa, chill out!" bob "ZOMG THE %^*@#$(*^ ZOMBIES ARE COMING!!11!!1!"
