~ "meetup.ua" ~ Hello
: >date-only \d -- d
d:/0 3 a:slice [0 0 0 0 0 0 0] a:+ d:⊂

"when teenth Monday is the 13th, the first day of the teenth week"
(2013 5 "Monday" "teenth" meetup >date-only)
[2013 5 13 0 0 0 0 0 0 0] d:⊂
=?

"when teenth Monday is the 19th, the last day of the teenth week"
(2013 8 "Monday" "teenth" meetup >date-only)
[2013 8 19 0 0 0 0 0 0 0] d:⊂
=?

"when teenth Monday is some day in the middle of the teenth week"
(2013 9 "Monday" "teenth" meetup >date-only)
[2013 9 16 0 0 0 0 0 0 0] d:⊂
=?

"when teenth Tuesday is the 19th, the last day of the teenth week"
(2013 3 "Tuesday" "teenth" meetup >date-only)
[2013 3 19 0 0 0 0 0 0 0] d:⊂
=?

"when teenth Tuesday is some day in the middle of the teenth week"
(2013 4 "Tuesday" "teenth" meetup >date-only)
[2013 4 16 0 0 0 0 0 0 0] d:⊂
=?

"when teenth Tuesday is the 13th, the first day of the teenth week"
(2013 8 "Tuesday" "teenth" meetup >date-only)
[2013 8 13 0 0 0 0 0 0 0] d:⊂
=?

"when teenth Wednesday is some day in the middle of the teenth week"
(2013 1 "Wednesday" "teenth" meetup >date-only)
[2013 1 16 0 0 0 0 0 0 0] d:⊂
=?

"when teenth Wednesday is the 13th, the first day of the teenth week"
(2013 2 "Wednesday" "teenth" meetup >date-only)
[2013 2 13 0 0 0 0 0 0 0] d:⊂
=?

"when teenth Wednesday is the 19th, the last day of the teenth week"
(2013 6 "Wednesday" "teenth" meetup >date-only)
[2013 6 19 0 0 0 0 0 0 0] d:⊂
=?

"when teenth Thursday is some day in the middle of the teenth week"
(2013 5 "Thursday" "teenth" meetup >date-only)
[2013 5 16 0 0 0 0 0 0 0] d:⊂
=?

"when teenth Thursday is the 13th, the first day of the teenth week"
(2013 6 "Thursday" "teenth" meetup >date-only)
[2013 6 13 0 0 0 0 0 0 0] d:⊂
=?

"when teenth Thursday is the 19th, the last day of the teenth week"
(2013 9 "Thursday" "teenth" meetup >date-only)
[2013 9 19 0 0 0 0 0 0 0] d:⊂
=?

"when teenth Friday is the 19th, the last day of the teenth week"
(2013 4 "Friday" "teenth" meetup >date-only)
[2013 4 19 0 0 0 0 0 0 0] d:⊂
=?

"when teenth Friday is some day in the middle of the teenth week"
(2013 8 "Friday" "teenth" meetup >date-only)
[2013 8 16 0 0 0 0 0 0 0] d:⊂
=?

"when teenth Friday is the 13th, the first day of the teenth week"
(2013 9 "Friday" "teenth" meetup >date-only)
[2013 9 13 0 0 0 0 0 0 0] d:⊂
=?

"when teenth Saturday is some day in the middle of the teenth week"
(2013 2 "Saturday" "teenth" meetup >date-only)
[2013 2 16 0 0 0 0 0 0 0] d:⊂
=?

"when teenth Saturday is the 13th, the first day of the teenth week"
(2013 4 "Saturday" "teenth" meetup >date-only)
[2013 4 13 0 0 0 0 0 0 0] d:⊂
=?

"when teenth Saturday is the 19th, the last day of the teenth week"
(2013 10 "Saturday" "teenth" meetup >date-only)
[2013 10 19 0 0 0 0 0 0 0] d:⊂
=?

"when teenth Sunday is the 19th, the last day of the teenth week"
(2013 5 "Sunday" "teenth" meetup >date-only)
[2013 5 19 0 0 0 0 0 0 0] d:⊂
=?

"when teenth Sunday is some day in the middle of the teenth week"
(2013 6 "Sunday" "teenth" meetup >date-only)
[2013 6 16 0 0 0 0 0 0 0] d:⊂
=?

"when teenth Sunday is the 13th, the first day of the teenth week"
(2013 10 "Sunday" "teenth" meetup >date-only)
[2013 10 13 0 0 0 0 0 0 0] d:⊂
=?

"when first Monday is some day in the middle of the first week"
(2013 3 "Monday" "first" meetup >date-only)
[2013 3 4 0 0 0 0 0 0 0] d:⊂
=?

"when first Monday is the 1st, the first day of the first week"
(2013 4 "Monday" "first" meetup >date-only)
[2013 4 1 0 0 0 0 0 0 0] d:⊂
=?

"when first Tuesday is the 7th, the last day of the first week"
(2013 5 "Tuesday" "first" meetup >date-only)
[2013 5 7 0 0 0 0 0 0 0] d:⊂
=?

"when first Tuesday is some day in the middle of the first week"
(2013 6 "Tuesday" "first" meetup >date-only)
[2013 6 4 0 0 0 0 0 0 0] d:⊂
=?

"when first Wednesday is some day in the middle of the first week"
(2013 7 "Wednesday" "first" meetup >date-only)
[2013 7 3 0 0 0 0 0 0 0] d:⊂
=?

"when first Wednesday is the 7th, the last day of the first week"
(2013 8 "Wednesday" "first" meetup >date-only)
[2013 8 7 0 0 0 0 0 0 0] d:⊂
=?

"when first Thursday is some day in the middle of the first week"
(2013 9 "Thursday" "first" meetup >date-only)
[2013 9 5 0 0 0 0 0 0 0] d:⊂
=?

"when first Thursday is another day in the middle of the first week"
(2013 10 "Thursday" "first" meetup >date-only)
[2013 10 3 0 0 0 0 0 0 0] d:⊂
=?

"when first Friday is the 1st, the first day of the first week"
(2013 11 "Friday" "first" meetup >date-only)
[2013 11 1 0 0 0 0 0 0 0] d:⊂
=?

"when first Friday is some day in the middle of the first week"
(2013 12 "Friday" "first" meetup >date-only)
[2013 12 6 0 0 0 0 0 0 0] d:⊂
=?

"when first Saturday is some day in the middle of the first week"
(2013 1 "Saturday" "first" meetup >date-only)
[2013 1 5 0 0 0 0 0 0 0] d:⊂
=?

"when first Saturday is another day in the middle of the first week"
(2013 2 "Saturday" "first" meetup >date-only)
[2013 2 2 0 0 0 0 0 0 0] d:⊂
=?

"when first Sunday is some day in the middle of the first week"
(2013 3 "Sunday" "first" meetup >date-only)
[2013 3 3 0 0 0 0 0 0 0] d:⊂
=?

"when first Sunday is the 7th, the last day of the first week"
(2013 4 "Sunday" "first" meetup >date-only)
[2013 4 7 0 0 0 0 0 0 0] d:⊂
=?

"when second Monday is some day in the middle of the second week"
(2013 3 "Monday" "second" meetup >date-only)
[2013 3 11 0 0 0 0 0 0 0] d:⊂
=?

"when second Monday is the 8th, the first day of the second week"
(2013 4 "Monday" "second" meetup >date-only)
[2013 4 8 0 0 0 0 0 0 0] d:⊂
=?

"when second Tuesday is the 14th, the last day of the second week"
(2013 5 "Tuesday" "second" meetup >date-only)
[2013 5 14 0 0 0 0 0 0 0] d:⊂
=?

"when second Tuesday is some day in the middle of the second week"
(2013 6 "Tuesday" "second" meetup >date-only)
[2013 6 11 0 0 0 0 0 0 0] d:⊂
=?

"when second Wednesday is some day in the middle of the second week"
(2013 7 "Wednesday" "second" meetup >date-only)
[2013 7 10 0 0 0 0 0 0 0] d:⊂
=?

"when second Wednesday is the 14th, the last day of the second week"
(2013 8 "Wednesday" "second" meetup >date-only)
[2013 8 14 0 0 0 0 0 0 0] d:⊂
=?

"when second Thursday is some day in the middle of the second week"
(2013 9 "Thursday" "second" meetup >date-only)
[2013 9 12 0 0 0 0 0 0 0] d:⊂
=?

"when second Thursday is another day in the middle of the second week"
(2013 10 "Thursday" "second" meetup >date-only)
[2013 10 10 0 0 0 0 0 0 0] d:⊂
=?

"when second Friday is the 8th, the first day of the second week"
(2013 11 "Friday" "second" meetup >date-only)
[2013 11 8 0 0 0 0 0 0 0] d:⊂
=?

"when second Friday is some day in the middle of the second week"
(2013 12 "Friday" "second" meetup >date-only)
[2013 12 13 0 0 0 0 0 0 0] d:⊂
=?

"when second Saturday is some day in the middle of the second week"
(2013 1 "Saturday" "second" meetup >date-only)
[2013 1 12 0 0 0 0 0 0 0] d:⊂
=?

"when second Saturday is another day in the middle of the second week"
(2013 2 "Saturday" "second" meetup >date-only)
[2013 2 9 0 0 0 0 0 0 0] d:⊂
=?

"when second Sunday is some day in the middle of the second week"
(2013 3 "Sunday" "second" meetup >date-only)
[2013 3 10 0 0 0 0 0 0 0] d:⊂
=?

"when second Sunday is the 14th, the last day of the second week"
(2013 4 "Sunday" "second" meetup >date-only)
[2013 4 14 0 0 0 0 0 0 0] d:⊂
=?

"when third Monday is some day in the middle of the third week"
(2013 3 "Monday" "third" meetup >date-only)
[2013 3 18 0 0 0 0 0 0 0] d:⊂
=?

"when third Monday is the 15th, the first day of the third week"
(2013 4 "Monday" "third" meetup >date-only)
[2013 4 15 0 0 0 0 0 0 0] d:⊂
=?

"when third Tuesday is the 21st, the last day of the third week"
(2013 5 "Tuesday" "third" meetup >date-only)
[2013 5 21 0 0 0 0 0 0 0] d:⊂
=?

"when third Tuesday is some day in the middle of the third week"
(2013 6 "Tuesday" "third" meetup >date-only)
[2013 6 18 0 0 0 0 0 0 0] d:⊂
=?

"when third Wednesday is some day in the middle of the third week"
(2013 7 "Wednesday" "third" meetup >date-only)
[2013 7 17 0 0 0 0 0 0 0] d:⊂
=?

"when third Wednesday is the 21st, the last day of the third week"
(2013 8 "Wednesday" "third" meetup >date-only)
[2013 8 21 0 0 0 0 0 0 0] d:⊂
=?

"when third Thursday is some day in the middle of the third week"
(2013 9 "Thursday" "third" meetup >date-only)
[2013 9 19 0 0 0 0 0 0 0] d:⊂
=?

"when third Thursday is another day in the middle of the third week"
(2013 10 "Thursday" "third" meetup >date-only)
[2013 10 17 0 0 0 0 0 0 0] d:⊂
=?

"when third Friday is the 15th, the first day of the third week"
(2013 11 "Friday" "third" meetup >date-only)
[2013 11 15 0 0 0 0 0 0 0] d:⊂
=?

"when third Friday is some day in the middle of the third week"
(2013 12 "Friday" "third" meetup >date-only)
[2013 12 20 0 0 0 0 0 0 0] d:⊂
=?

"when third Saturday is some day in the middle of the third week"
(2013 1 "Saturday" "third" meetup >date-only)
[2013 1 19 0 0 0 0 0 0 0] d:⊂
=?

"when third Saturday is another day in the middle of the third week"
(2013 2 "Saturday" "third" meetup >date-only)
[2013 2 16 0 0 0 0 0 0 0] d:⊂
=?

"when third Sunday is some day in the middle of the third week"
(2013 3 "Sunday" "third" meetup >date-only)
[2013 3 17 0 0 0 0 0 0 0] d:⊂
=?

"when third Sunday is the 21st, the last day of the third week"
(2013 4 "Sunday" "third" meetup >date-only)
[2013 4 21 0 0 0 0 0 0 0] d:⊂
=?

"when fourth Monday is some day in the middle of the fourth week"
(2013 3 "Monday" "fourth" meetup >date-only)
[2013 3 25 0 0 0 0 0 0 0] d:⊂
=?

"when fourth Monday is the 22nd, the first day of the fourth week"
(2013 4 "Monday" "fourth" meetup >date-only)
[2013 4 22 0 0 0 0 0 0 0] d:⊂
=?

"when fourth Tuesday is the 28th, the last day of the fourth week"
(2013 5 "Tuesday" "fourth" meetup >date-only)
[2013 5 28 0 0 0 0 0 0 0] d:⊂
=?

"when fourth Tuesday is some day in the middle of the fourth week"
(2013 6 "Tuesday" "fourth" meetup >date-only)
[2013 6 25 0 0 0 0 0 0 0] d:⊂
=?

"when fourth Wednesday is some day in the middle of the fourth week"
(2013 7 "Wednesday" "fourth" meetup >date-only)
[2013 7 24 0 0 0 0 0 0 0] d:⊂
=?

"when fourth Wednesday is the 28th, the last day of the fourth week"
(2013 8 "Wednesday" "fourth" meetup >date-only)
[2013 8 28 0 0 0 0 0 0 0] d:⊂
=?

"when fourth Thursday is some day in the middle of the fourth week"
(2013 9 "Thursday" "fourth" meetup >date-only)
[2013 9 26 0 0 0 0 0 0 0] d:⊂
=?

"when fourth Thursday is another day in the middle of the fourth week"
(2013 10 "Thursday" "fourth" meetup >date-only)
[2013 10 24 0 0 0 0 0 0 0] d:⊂
=?

"when fourth Friday is the 22nd, the first day of the fourth week"
(2013 11 "Friday" "fourth" meetup >date-only)
[2013 11 22 0 0 0 0 0 0 0] d:⊂
=?

"when fourth Friday is some day in the middle of the fourth week"
(2013 12 "Friday" "fourth" meetup >date-only)
[2013 12 27 0 0 0 0 0 0 0] d:⊂
=?

"when fourth Saturday is some day in the middle of the fourth week"
(2013 1 "Saturday" "fourth" meetup >date-only)
[2013 1 26 0 0 0 0 0 0 0] d:⊂
=?

"when fourth Saturday is another day in the middle of the fourth week"
(2013 2 "Saturday" "fourth" meetup >date-only)
[2013 2 23 0 0 0 0 0 0 0] d:⊂
=?

"when fourth Sunday is some day in the middle of the fourth week"
(2013 3 "Sunday" "fourth" meetup >date-only)
[2013 3 24 0 0 0 0 0 0 0] d:⊂
=?

"when fourth Sunday is the 28th, the last day of the fourth week"
(2013 4 "Sunday" "fourth" meetup >date-only)
[2013 4 28 0 0 0 0 0 0 0] d:⊂
=?

"last Monday in a month with four Mondays"
(2013 3 "Monday" "last" meetup >date-only)
[2013 3 25 0 0 0 0 0 0 0] d:⊂
=?

"last Monday in a month with five Mondays"
(2013 4 "Monday" "last" meetup >date-only)
[2013 4 29 0 0 0 0 0 0 0] d:⊂
=?

"last Tuesday in a month with four Tuesdays"
(2013 5 "Tuesday" "last" meetup >date-only)
[2013 5 28 0 0 0 0 0 0 0] d:⊂
=?

"last Tuesday in another month with four Tuesdays"
(2013 6 "Tuesday" "last" meetup >date-only)
[2013 6 25 0 0 0 0 0 0 0] d:⊂
=?

"last Wednesday in a month with five Wednesdays"
(2013 7 "Wednesday" "last" meetup >date-only)
[2013 7 31 0 0 0 0 0 0 0] d:⊂
=?

"last Wednesday in a month with four Wednesdays"
(2013 8 "Wednesday" "last" meetup >date-only)
[2013 8 28 0 0 0 0 0 0 0] d:⊂
=?

"last Thursday in a month with four Thursdays"
(2013 9 "Thursday" "last" meetup >date-only)
[2013 9 26 0 0 0 0 0 0 0] d:⊂
=?

"last Thursday in a month with five Thursdays"
(2013 10 "Thursday" "last" meetup >date-only)
[2013 10 31 0 0 0 0 0 0 0] d:⊂
=?

"last Friday in a month with five Fridays"
(2013 11 "Friday" "last" meetup >date-only)
[2013 11 29 0 0 0 0 0 0 0] d:⊂
=?

"last Friday in a month with four Fridays"
(2013 12 "Friday" "last" meetup >date-only)
[2013 12 27 0 0 0 0 0 0 0] d:⊂
=?

"last Saturday in a month with four Saturdays"
(2013 1 "Saturday" "last" meetup >date-only)
[2013 1 26 0 0 0 0 0 0 0] d:⊂
=?

"last Saturday in another month with four Saturdays"
(2013 2 "Saturday" "last" meetup >date-only)
[2013 2 23 0 0 0 0 0 0 0] d:⊂
=?

"last Sunday in a month with five Sundays"
(2013 3 "Sunday" "last" meetup >date-only)
[2013 3 31 0 0 0 0 0 0 0] d:⊂
=?

"last Sunday in a month with four Sundays"
(2013 4 "Sunday" "last" meetup >date-only)
[2013 4 28 0 0 0 0 0 0 0] d:⊂
=?

"when last Wednesday in February in a leap year is the 29th"
(2012 2 "Wednesday" "last" meetup >date-only)
[2012 2 29 0 0 0 0 0 0 0] d:⊂
=?

"last Wednesday in December that is also the last day of the year"
(2014 12 "Wednesday" "last" meetup >date-only)
[2014 12 31 0 0 0 0 0 0 0] d:⊂
=?

"when last Sunday in February in a non-leap year is not the 29th"
(2015 2 "Sunday" "last" meetup >date-only)
[2015 2 22 0 0 0 0 0 0 0] d:⊂
=?

"when first Friday is the 7th, the last day of the first week"
(2012 12 "Friday" "first" meetup >date-only)
[2012 12 7 0 0 0 0 0 0 0] d:⊂
=?
